"""Extend history model

Revision ID: 9fe4d9db1762
Revises: 
Create Date: 2026-05-29 00:55:17.586524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe4d9db1762'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('destination', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('preference', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('selected_mode', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('selected_mode')
        batch_op.drop_column('preference')
        batch_op.drop_column('destination')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
